AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  myBucket1Name:
    Type: String
Resources:
  myS3Bucket1:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: 
        Ref: 'myBucket1Name'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
