AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myS3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
           Status: Suspended
      Tags:
        - Key: Key1
          Value: sample1