AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myS3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
           Status: Enabled
      Tags:
        - Key: Key1
          Value: sample1
        - Key: Key2
          Value: sample2
