AWSTemplateFormatVersion: 2010-09-09
Resources:
  myUser01:
    Type: AWS::IAM::User
    Properties:
      LoginProfile: 
        Password: '{{resolve:secretsmanager:userinfo01:SecretString:password}}'
        PasswordResetRequired: true
      UserName:   '{{resolve:secretsmanager:userinfo01:SecretString:username}}'
