AWSTemplateFormatVersion: '2010-09-09'
Resources:
 mySecret4DB:
  Type: 'AWS::SecretsManager::Secret'
  Properties:
    Name: MyRDSSecret4dbuser1
    Description: "This secret has a dynamically generated secret password."
    GenerateSecretString:
      SecretStringTemplate: '{"username": "dbuser1"}'
      GenerateStringKey: "password"
      PasswordLength: 30
      ExcludeCharacters: |-
         "'/\;(){}[]<> =
