AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  myImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: PP-Project-AMI-x86_64:1

Resources:
  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref myImageId
      InstanceType: t3.nano
