Parameters:
  EnvType:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
Conditions:
  CreateProdResources: !Equals 
    - !Ref EnvType
    - prod
Resources:
  S3bucket4Prod:
    Type: 'AWS::S3::Bucket'
    Condition: CreateProdResources
