AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'
Parameters:
  paramBucketPrefixList:
    Description: Bucket Name Prefix
    Type: CommaDelimitedList
    Default: 's3log,s3data,s3work'
Resources:
  Fn::ForEach::BucketAndPolicy:
    - BucketPrefix
    - Ref: paramBucketPrefixList
    - 'my${BucketPrefix}bucket':
        Type: AWS::S3::Bucket
        Properties:
          BucketName: !Sub '${BucketPrefix}-${AWS::AccountId}'
      'my${BucketPrefix}bucketPolicy':
        Type: AWS::S3::BucketPolicy
        Properties:
          Bucket:
            Ref:
              Fn::Sub: 'my${BucketPrefix}bucket'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: RestrictToTLSRequestsOnly
                Action: s3:*
                Effect: Deny
                Resource:
                  - Fn::Sub: 'arn:aws:s3:::${BucketPrefix}-${AWS::AccountId}'
                  - Fn::Sub: 'arn:aws:s3:::${BucketPrefix}-${AWS::AccountId}/*'
                Condition:
                  Bool:
                    aws:SecureTransport: 'false'
                Principal: '*'
