AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  mySAMFunct:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      InlineCode: |
        import logging
        logger = logging.getLogger()
        logger.setLevel(logging.INFO)
        def handler(event, context):
          print("CloudWatch log group name:",  context.log_group_name)
          logger.info('## EVENT')
          logger.info(event)
          return {'body': 'Hello World!', 'statusCode': 200}
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
