AWSTemplateFormatVersion: 2010-09-09
Resources:
  RdsSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: vpc-07e46b23f18458d6c
      GroupDescription: allow rds connect from AtEx
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: '192.168.0.0/16'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !GetAtt AtExSG.GroupId
      Tags:
        - Key: Name
          Value: RdsSG

  AtExSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: vpc-07e46b23f18458d6c
      GroupDescription: allow rds connect to RdsSG
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          DestinationSecurityGroupId: !GetAtt RdsSG.GroupId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: AtExSG
